jobs:
  pyinstaller-build:
    runs-on: <windows-latest / ubuntu-latest / ..... etc>
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'nhentai2CBZ.py'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'Nhentai2CBZ'
          options: --onefile, --name "Nhentai2CBZ", --windowed, 
